FROM node:22-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN npx nx build forgive-front

EXPOSE 3000

CMD ["node", "dist/apps/forgive-front/.output/server/index.mjs"]
